name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --group dev

      - name: Check imports sort order
        run: uv run isort --profile black --check-only --diff src tests

      - name: Check formatting
        run: uv run black --check --diff src tests

      - name: Check typing
        run: uv run mypy

      - name: Test
        run: uv run pytest --cov gems --cov-report xml

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: python-code-coverage-report
          path: coverage.xml
